name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    uses: wetransform/gha-workflows/.github/workflows/gradle-library-check.yml@v2.5.0 # v2.5.0
    with:
      java-version: 11
