name: Release

on:
  workflow_dispatch: 

env:
  # renovate: datasource=npm depName=@semantic-release/changelog
  SEMANTIC_RELEASE_CHANGELOG_VERSION: 6.0.3

  # renovate: datasource=npm depName=@semantic-release/exec
  SEMANTIC_RELEASE_EXEC_VERSION: 6.0.3

  # renovate: datasource=npm depName=@semantic-release/git
  SEMANTIC_RELEASE_GIT_VERSION: 10.0.1

  # renovate: datasource=npm depName=conventional-changelog-conventionalcommits
  CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION: 7.0.2

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-release

    outputs:
      release-published: ${{ steps.release.outputs.new_release_published }}
      release-version: ${{ steps.release.outputs.new_release_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v4.1.7
        with:
          persist-credentials: false

      - name: "Install Node"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Setup Java
        uses: actions/setup-java@v4 # v4.2.2
        with:
          distribution: temurin
          java-version: 11

 
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4 # v4.0.0

      - name: Build project
        run: ./gradlew clean | ./gradlew build

      - name: Configure Maven settings.xml
        run: |
          mkdir -p ~/.m2/settings.xml
          echo '<settings><servers><server><id>github</id><username>tianyingchun</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>' > ~/.m2/settings.xml

      - name: Release
        id: release
        uses: cycjimmy/semantic-release-action@v4 # v4.1.0
        env:
          # Permissions needed
          #   contents: write
          #   issues: write
          #   pull-requests: write
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GIT_AUTHOR_NAME: wetransform Bot
          # GIT_AUTHOR_EMAIL: 113353961+wetransformer@users.noreply.github.com
          # GIT_COMMITTER_NAME: wetransform Bot
          # GIT_COMMITTER_EMAIL: 113353961+wetransformer@users.noreply.github.com
          RUNNER_DEBUG: 1
          # For Gradle execution
          # GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          # GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
        with:
          # dry_run: true
          semantic_version: 23.1.1
          
          extra_plugins:
            "@semantic-release/changelog@\
            ${{ env.SEMANTIC_RELEASE_CHANGELOG_VERSION }} \
            @semantic-release/exec@\
            ${{ env.SEMANTIC_RELEASE_EXEC_VERSION }} \
            @semantic-release/git@\
            ${{ env.SEMANTIC_RELEASE_GIT_VERSION }} \
            conventional-changelog-conventionalcommits@\
            ${{ env.CONVENTIONAL_CHANGELOG_CONVENTIONALCOMMITS_VERSION }} \
            "
